### ISSUE TITLE
Docs stating hard-coded assumptions

### ISSUE THREAD

**Issue by nick-youngblut** [VectorInstitute/vector-inference#4]
Thanks for the resource! 

The docs make some assumptions about the user's compute environment, but do not warn the user about these assumptions:

* `venv.sh`
  * `module` is installed and `python/3.10.12` is available
  * `/scratch/ssd004/` exists
* `README.md`
  * `/pkgs/cuda-12.3` is the location of CUDA HOME, or the user has something similar. In my case: `CUDA_HOME=/usr/local/cuda/`
* `models/llama3/launch_server.sh`
    * The `a40` partition exists
* `examples/inference.py`
  * It is not clear what the user must edit in `http://gpuXXX:XXXXX/v1`
  * Also `http://gpuXXX:XXXXX/v1` is hard-coded
  * The `models/llama3/launch_server.sh` example uses llama3-8b, but `examples/inference.py` hard-codes `Llama-2-70b-hf`
  * It is unclear how to properly edit `model="/model-weights/Llama-2-70b-hf"`, depending on the LLM used

**Comment by nick-youngblut** [comment]
Here's my current setup, which uses conda (mamba) instead of `module` and a `poetry` venv:

```bash
mamba create -n vector-inference -y python=3.10.12 poetry \
  && mamba activate vector-inference

git clone https://github.com/VectorInstitute/vector-inference.git \
  && cd vector-inference
  
poetry install

export CUDA_HOME=/usr/local/cuda/

pip install flash-attn --no-build-isolation \
  && pip install vllm-flash-attn torch==2.3.0 
```

**Comment by XkunW** [comment]
Hi Nick, 

Thanks for raising these concerns. As mentioned in the README, everything in this repo is designed around the Vector Institute Slurm cluster environment, and you would need to make certain adjustments in order to adapt to your own Slurm cluster. We are very interested into making this a more generic solution for others, and we'd be happy to set up a time to chat more with you on how we can improve the repo.

In the meantime, regarding the points you mentioned:

- The `module load python/3.10.12` is just specifying the python version to use on our cluster, so as long as you have python 3.10 in your environment, you don't need this step. As for the `/scratch/ssd004` space, that's also just additional storage in our environment that is better suited for cache directories, and like I mentioned in the comments this is an optional step.
- As addressed in the comment, change this path according to your environment
- The `a40` partition is just the default I set for our environment, you can easily overwrite this with a flag, and you can find more about all the available flags and environment variables in [`/models/README.md`](/models/README.md). With regards to your other question, I'm not sure I quite understand, if you could elaborate more that'd be great.
- In the corresponding model directory, after you've launched your model, you should see a file named like `.vLLM_${MODEL_NAME}-${MODEL_VARIANT}_url`, replace the provided with the url generated in that file. Regarding the `/model-weights` folder, that's where we keep our downloaded model weights, so just change the path to where you stored the corresponding model weights. The scripts in example folder are just references for how to inference the hosted models, you would need to change the URL and the model weights path according to your setup.

We are very close to cutting a new release, which will come with better documentation and simpler structure, the latest progress can be found in `develop` branch.

**Comment by nick-youngblut** [comment]
Thanks @XkunW for the detailed info! Also, thanks again for making the repo public. I definitely understand that it's not plug-and-play, but it is helpful to have a bit more docs on what would need to be changes for running on other SLURM clusters. 
Thanks for letting me know about the new release on the `develop` branch. 
I can provide some info on running the models on H100 GPUs, if you think that info would be useful for this repo.

**Comment by XkunW** [comment]
That would be awesome! If you want you can branch off of `develop`, add the info to the model README files and open a PR. Or we can find some time to chat more:)

**Comment by nick-youngblut** [comment]
> That would be awesome! 

Great! I'm still testing, but right now I'm running `Meta-Llama-3-70B-Instruct` on 4 H100 GPUs with:

```bash
python -m vllm.entrypoints.openai.api_server \
  --model meta-llama/Meta-Llama-3-70B-Instruct \
  --port 8000 \
  --host "0.0.0.0" \
  --tensor-parallel-size 4 \
  --dtype float16
```
